application: kate-and-avi-o
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: (/|/index\.html)
  static_files: static/index.html
  upload: static/index.html
